camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    authorization:
      enabled: true
    database:
      type: postgres
    table-prefix: camunda.
    schema-update: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda?stringtype=unspecified
    username: demo
    password: demoP@ssw0rd